import React from "react";
import firstimage from "../../images/instagram-users-by-country-2023-december.png";
import "./msp.css";

function ML() {
  return (
    <div className="card">
      <h5 className="card-header">Top 20 Most Liked Instagram Posts in 2023</h5>
      <div className="card-body">
        <div className="form-group">
          <div className="">
            <div className="">
              <div className="">
                <div className="">
                <div className="article">
  <h1>Instagram Users by Country 2023</h1>
  <div className="article__content">
    <p>
      The penetration rate of social networks in the world is increasing at a
      great pace. In the last eight years, the penetration rate has doubled.
      Among the fastest growing social networks is Instagram. The largest number
      of users of this social network is in India. This is due to both the large
      population and the outpacing growth of telecommunications networks in this
      country.
    </p>
    <p>
      In 2015, less than 30% of the world's population used social networks.
      However, thanks to the development of the Internet and the pandemic years
      2020-2021, this figure has increased to 50.4%. According to GSMA
      Intelligence, a global association of mobile operators, this figure will
      reach 60% by mid-2023. This trend suggests that the next few years will
      also see a strong growth in social media usage.
    </p>
    <p>
      North America has the highest social media penetration rate in relation to
      the total population of this continent. It accounts for 3/4 of the total
      population. Northern and Western Europe are also not lagging behind. These
      regions are home to fairly affluent populations that utilize high-speed
      Internet. Social networks have penetrated into many spheres of people's
      lives: tourism, shopping, sports and many other spheres.
    </p>
    <h2>Countries with the most Instagram users 2023</h2>
    <p>
      <em>
        Statistics data&nbsp;
        <span style={{ fontWeight: 400 }}>
          correct as of December 10, 2023.
        </span>
      </em>
    </p>
    <p>
      This table presents statistics for countries around the world. According
      to this data, you can roughly estimate how much of the population uses
      Instagram.
    </p>
    <table width="100%">
      <thead>
        <tr>
          <th>
            <strong>Country</strong>
          </th>
          <th>Instagram users</th>
          <th>Population</th>
          <th>Population using Instagram, % *</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <strong>India</strong>
          </td>
          <td>374,300,000&nbsp;</td>
          <td>1,434,338,708</td>
          <td>26,10</td>
        </tr>
        <tr>
          <td>
            <strong>United States</strong>
          </td>
          <td>172,622,500</td>
          <td>340,789,335</td>
          <td>50,65</td>
        </tr>
        <tr>
          <td>
            <strong>Brazil</strong>
          </td>
          <td>138,812,200</td>
          <td>216,959,035</td>
          <td>63,98</td>
        </tr>
        <tr>
          <td>
            <strong>Indonesia</strong>
          </td>
          <td>96,965,500</td>
          <td>278,527,099</td>
          <td>34,81</td>
        </tr>
        <tr>
          <td>
            <strong>Russia</strong>
          </td>
          <td>63,924,100</td>
          <td>144,228,279</td>
          <td>44,32</td>
        </tr>
        <tr>
          <td>
            <strong>Turkey</strong>
          </td>
          <td>60,314,100</td>
          <td>86,011,165</td>
          <td>70,12</td>
        </tr>
        <tr>
          <td>
            <strong>Japan</strong>
          </td>
          <td>58,852,700</td>
          <td>123,008,525</td>
          <td>47,84</td>
        </tr>
        <tr>
          <td>
            <strong>Mexico</strong>
          </td>
          <td>49,359,300</td>
          <td>128,863,450</td>
          <td>38,30</td>
        </tr>
        <tr>
          <td>
            <strong>United Kingdom</strong>
          </td>
          <td>35,148,100</td>
          <td>67,834,772</td>
          <td>51,81</td>
        </tr>
        <tr>
          <td>
            <strong>Germany</strong>
          </td>
          <td>33,928,100</td>
          <td>83,278,832</td>
          <td>40,74</td>
        </tr>
        <tr>
          <td>
            <strong>Italy</strong>
          </td>
          <td>28,800,000</td>
          <td>58,797,409</td>
          <td>48,98</td>
        </tr>
        <tr>
          <td>
            <strong>Argentina</strong>
          </td>
          <td>28,691,400</td>
          <td>45,897,767</td>
          <td>62,51</td>
        </tr>
        <tr>
          <td>
            <strong>France</strong>
          </td>
          <td>27,436,900</td>
          <td>64,811,844</td>
          <td>42,33</td>
        </tr>
        <tr>
          <td>
            <strong>Spain</strong>
          </td>
          <td>25,499,200</td>
          <td>47,501,091</td>
          <td>53,68</td>
        </tr>
        <tr>
          <td>
            <strong>South Korea</strong>
          </td>
          <td>24,663,400</td>
          <td>51,768,022</td>
          <td>47,64</td>
        </tr>
        <tr>
          <td>
            <strong>Philippines</strong>
          </td>
          <td>22,993,600</td>
          <td>118,103,618</td>
          <td>19,47</td>
        </tr>
        <tr>
          <td>
            <strong>Thailand</strong>
          </td>
          <td>21,185,800&nbsp;</td>
          <td>71,842,351</td>
          <td>29,49</td>
        </tr>
        <tr>
          <td>
            <strong>Colombia</strong>
          </td>
          <td>21,118,100</td>
          <td>52,194,132</td>
          <td>40,46</td>
        </tr>
        <tr>
          <td>
            <strong>Canada</strong>
          </td>
          <td>19,892,000</td>
          <td>38,922,730</td>
          <td>51,11</td>
        </tr>
        <tr>
          <td>
            <strong>Egypt</strong>
          </td>
          <td>19,386,700</td>
          <td>113,468,597</td>
          <td>17,09</td>
        </tr>
        <tr>
          <td>
            <strong>Iraq</strong>
          </td>
          <td>19,010,200</td>
          <td>45,944,482</td>
          <td>41,38</td>
        </tr>
        <tr>
          <td>
            <strong>Pakistan</strong>
          </td>
          <td>17,645,300</td>
          <td>242,527,042</td>
          <td>7,28</td>
        </tr>
        <tr>
          <td>
            <strong>Saudi Arabia</strong>
          </td>
          <td>16,481,700</td>
          <td>37,177,108</td>
          <td>44,33</td>
        </tr>
        <tr>
          <td>
            <strong>Malaysia</strong>
          </td>
          <td>15,953,600</td>
          <td>34,467,262</td>
          <td>46,29</td>
        </tr>
        <tr>
          <td>
            <strong>Australia</strong>
          </td>
          <td>14,363,700</td>
          <td>26,552,050</td>
          <td>54,10</td>
        </tr>
        <tr>
          <td>
            <strong>Chile</strong>
          </td>
          <td>13,210,000</td>
          <td>19,642,179</td>
          <td>67,25</td>
        </tr>
        <tr>
          <td>
            <strong>Ukraine</strong>
          </td>
          <td>13,026,600</td>
          <td>37,328,924</td>
          <td>34,90</td>
        </tr>
        <tr>
          <td>
            <strong>Nigeria</strong>
          </td>
          <td>12,898,500</td>
          <td>226,097,862</td>
          <td>5,70</td>
        </tr>
        <tr>
          <td>
            <strong>Morocco</strong>
          </td>
          <td>12,396,300</td>
          <td>38,003,190</td>
          <td>32,62</td>
        </tr>
        <tr>
          <td>
            <strong>Kazakhstan</strong>
          </td>
          <td>12,216,200</td>
          <td>19,698,459</td>
          <td>62,02</td>
        </tr>
        <tr>
          <td>
            <strong>Taiwan</strong>
          </td>
          <td>12,054,700</td>
          <td>23,935,627</td>
          <td>50,36</td>
        </tr>
        <tr>
          <td>
            <strong>Vietnam</strong>
          </td>
          <td>11,988,500</td>
          <td>99,142,304</td>
          <td>12,09</td>
        </tr>
        <tr>
          <td>
            <strong>Algeria</strong>
          </td>
          <td>11,767,500</td>
          <td>45,903,770</td>
          <td>25,64</td>
        </tr>
        <tr>
          <td>
            <strong>Poland</strong>
          </td>
          <td>11,524,400</td>
          <td>40,635,411</td>
          <td>28,36</td>
        </tr>
        <tr>
          <td>
            <strong>Peru</strong>
          </td>
          <td>10,645,900</td>
          <td>34,495,691</td>
          <td>30,86</td>
        </tr>
        <tr>
          <td>
            <strong>Venezuela</strong>
          </td>
          <td>8,512,000</td>
          <td>29,083,133</td>
          <td>29,27</td>
        </tr>
        <tr>
          <td>
            <strong>Netherlands</strong>
          </td>
          <td>8,306,400</td>
          <td>17,641,505</td>
          <td>47,08</td>
        </tr>
        <tr>
          <td>
            <strong>Uzbekistan</strong>
          </td>
          <td>8,169,000</td>
          <td>35,390,346</td>
          <td>23,08</td>
        </tr>
        <tr>
          <td>
            <strong>United Arab Emirates</strong>
          </td>
          <td>7,352,200</td>
          <td>9,549,640</td>
          <td>76,99</td>
        </tr>
        <tr>
          <td>
            <strong>South Africa</strong>
          </td>
          <td>7,198,300</td>
          <td>60,651,138</td>
          <td>11,87</td>
        </tr>
        <tr>
          <td>
            <strong>Bangladesh</strong>
          </td>
          <td>6,914,400</td>
          <td>173,714,937</td>
          <td>3,98</td>
        </tr>
        <tr>
          <td>
            <strong>Ecuador</strong>
          </td>
          <td>6,877,700</td>
          <td>18,271,749</td>
          <td>37,64</td>
        </tr>
        <tr>
          <td>
            <strong>Portugal</strong>
          </td>
          <td>6,159,600</td>
          <td>10,237,310</td>
          <td>60,17</td>
        </tr>
        <tr>
          <td>
            <strong>Sweden</strong>
          </td>
          <td>5,800,000</td>
          <td>10,638,960</td>
          <td>54,52</td>
        </tr>
        <tr>
          <td>
            <strong>Romania</strong>
          </td>
          <td>5,461,500</td>
          <td>19,751,838</td>
          <td>27,65</td>
        </tr>
        <tr>
          <td>
            <strong>Belgium</strong>
          </td>
          <td>5,139,700</td>
          <td>11,699,079</td>
          <td>43,93</td>
        </tr>
        <tr>
          <td>
            <strong>Dominican Republic</strong>
          </td>
          <td>4,901,700</td>
          <td>11,377,180</td>
          <td>43,08</td>
        </tr>
        <tr>
          <td>
            <strong>Israel</strong>
          </td>
          <td>4,562,800</td>
          <td>9,233,902</td>
          <td>49,41</td>
        </tr>
        <tr>
          <td>
            <strong>Greece</strong>
          </td>
          <td>4,541,300</td>
          <td>10,324,793</td>
          <td>43,98</td>
        </tr>
        <tr>
          <td>
            <strong>Azerbaijan</strong>
          </td>
          <td>4,281,400</td>
          <td>10,435,241</td>
          <td>41,03</td>
        </tr>
        <tr>
          <td>
            <strong>Belarus</strong>
          </td>
          <td>3,949,300</td>
          <td>9,479,403</td>
          <td>41,66</td>
        </tr>
        <tr>
          <td>
            <strong>Jordan</strong>
          </td>
          <td>3,914,600</td>
          <td>11,355,660</td>
          <td>34,47</td>
        </tr>
        <tr>
          <td>
            <strong>Switzerland</strong>
          </td>
          <td>3,762,300</td>
          <td>8,820,672</td>
          <td>42,65</td>
        </tr>
        <tr>
          <td>
            <strong>Czech Republic</strong>
          </td>
          <td>3,752,100</td>
          <td>10,499,468</td>
          <td>35,74</td>
        </tr>
        <tr>
          <td>
            <strong>Tanzania</strong>
          </td>
          <td>3,698,000</td>
          <td>68,287,872</td>
          <td>5,42</td>
        </tr>
        <tr>
          <td>
            <strong>Guatemala</strong>
          </td>
          <td>3,622,700</td>
          <td>18,201,820</td>
          <td>19,90</td>
        </tr>
        <tr>
          <td>
            <strong>Tunisia</strong>
          </td>
          <td>3,517,500</td>
          <td>12,505,536</td>
          <td>28,13</td>
        </tr>
        <tr>
          <td>
            <strong>Nepal</strong>
          </td>
          <td>3,498,200</td>
          <td>31,046,592</td>
          <td>11,27</td>
        </tr>
        <tr>
          <td>
            <strong>Austria</strong>
          </td>
          <td>3,393,600</td>
          <td>8,967,125</td>
          <td>37,84</td>
        </tr>
        <tr>
          <td>
            <strong>Serbia</strong>
          </td>
          <td>3,365,000</td>
          <td>7,121,332</td>
          <td>47,25</td>
        </tr>
        <tr>
          <td>
            <strong>Hong Kong</strong>
          </td>
          <td>3,341,000</td>
          <td>7,494,230</td>
          <td>44,58</td>
        </tr>
        <tr>
          <td>
            <strong>Singapore</strong>
          </td>
          <td>3,287,600</td>
          <td>6,031,376</td>
          <td>54,51</td>
        </tr>
        <tr>
          <td>
            <strong>Kenya</strong>
          </td>
          <td>3,049,100</td>
          <td>55,572,524</td>
          <td>5,49</td>
        </tr>
        <tr>
          <td>
            <strong>Kuwait</strong>
          </td>
          <td>2,908,700</td>
          <td>4,327,463</td>
          <td>67,21</td>
        </tr>
        <tr>
          <td>
            <strong>Kyrgyzstan</strong>
          </td>
          <td>2,877,200</td>
          <td>6,780,488</td>
          <td>42,43</td>
        </tr>
        <tr>
          <td>
            <strong>Hungary</strong>
          </td>
          <td>2,835,800</td>
          <td>10,078,521</td>
          <td>28,14</td>
        </tr>
        <tr>
          <td>
            <strong>Denmark</strong>
          </td>
          <td>2,716,900</td>
          <td>5,923,340</td>
          <td>45,87</td>
        </tr>
        <tr>
          <td>
            <strong>Norway</strong>
          </td>
          <td>2,711,300</td>
          <td>5,491,699</td>
          <td>49,37</td>
        </tr>
        <tr>
          <td>
            <strong>Panama</strong>
          </td>
          <td>2,632,000</td>
          <td>4,494,223</td>
          <td>58,56</td>
        </tr>
        <tr>
          <td>
            <strong>Paraguay</strong>
          </td>
          <td>2,667,400</td>
          <td>6,898,969</td>
          <td>38,66</td>
        </tr>
        <tr>
          <td>
            <strong>Lebanon</strong>
          </td>
          <td>2,616,800</td>
          <td>5,291,971</td>
          <td>49,45</td>
        </tr>
        <tr>
          <td>
            <strong>Costa Rica</strong>
          </td>
          <td>2,562,400</td>
          <td>5,227,381</td>
          <td>49,02</td>
        </tr>
        <tr>
          <td>
            <strong>New Zealand</strong>
          </td>
          <td>2,551,700</td>
          <td>5,246,449</td>
          <td>48,64</td>
        </tr>
        <tr>
          <td>
            <strong>Ireland</strong>
          </td>
          <td>2,549,700</td>
          <td>5,071,304</td>
          <td>50,28</td>
        </tr>
        <tr>
          <td>
            <strong>Oman</strong>
          </td>
          <td>2,398,500</td>
          <td>4,674,720</td>
          <td>51,31</td>
        </tr>
        <tr>
          <td>
            <strong>Bolivia</strong>
          </td>
          <td>2,352,500</td>
          <td>12,465,845</td>
          <td>18,87</td>
        </tr>
        <tr>
          <td>
            <strong>Finland</strong>
          </td>
          <td>2,321,500</td>
          <td>5,547,422</td>
          <td>41,85</td>
        </tr>
        <tr>
          <td>
            <strong>Ghana</strong>
          </td>
          <td>2,317,000</td>
          <td>34,402,948</td>
          <td>6,73</td>
        </tr>
        <tr>
          <td>
            <strong>Uruguay</strong>
          </td>
          <td>2,316,700</td>
          <td>3,423,228</td>
          <td>67,68</td>
        </tr>
        <tr>
          <td>
            <strong>Libya</strong>
          </td>
          <td>2,094,800</td>
          <td>6,921,612</td>
          <td>30,26</td>
        </tr>
        <tr>
          <td>
            <strong>Cambodia</strong>
          </td>
          <td>2,014,700</td>
          <td>17,022,471</td>
          <td>11,84</td>
        </tr>
        <tr>
          <td>
            <strong>Myanmar</strong>
          </td>
          <td>1,999,600</td>
          <td>54,748,541</td>
          <td>3,65</td>
        </tr>
        <tr>
          <td>
            <strong>Honduras</strong>
          </td>
          <td>1,974,300</td>
          <td>10,665,631</td>
          <td>18,51</td>
        </tr>
        <tr>
          <td>
            <strong>El Salvador</strong>
          </td>
          <td>1,902,400</td>
          <td>6,378,747</td>
          <td>29,82</td>
        </tr>
        <tr>
          <td>
            <strong>Bulgaria</strong>
          </td>
          <td>1,822,000</td>
          <td>6,650,889</td>
          <td>27,39</td>
        </tr>
        <tr>
          <td>
            <strong>Sri Lanka</strong>
          </td>
          <td>1,807,000</td>
          <td>21,918,818</td>
          <td>8,24</td>
        </tr>
        <tr>
          <td>
            <strong>Georgia</strong>
          </td>
          <td>1,799,400</td>
          <td>3,722,077</td>
          <td>48,34</td>
        </tr>
        <tr>
          <td>
            <strong>Qatar</strong>
          </td>
          <td>1,696,600</td>
          <td>2,725,455</td>
          <td>62,25</td>
        </tr>
        <tr>
          <td>
            <strong>Palestine</strong>
          </td>
          <td>1,622,100</td>
          <td>5,424,051</td>
          <td>29,91</td>
        </tr>
        <tr>
          <td>
            <strong>Slovakia</strong>
          </td>
          <td>1,664,100</td>
          <td>5,749,981</td>
          <td>28,94</td>
        </tr>
        <tr>
          <td>
            <strong>Puerto Rico</strong>
          </td>
          <td>1,537,900</td>
          <td>3,264,331</td>
          <td>47,11</td>
        </tr>
        <tr>
          <td>
            <strong>Yemen</strong>
          </td>
          <td>1,505,300</td>
          <td>34,777,652</td>
          <td>4,33</td>
        </tr>
        <tr>
          <td>
            <strong>Tajikistan</strong>
          </td>
          <td>1,484,300</td>
          <td>10,225,305</td>
          <td>14,52</td>
        </tr>
        <tr>
          <td>
            <strong>Croatia</strong>
          </td>
          <td>1,444,400</td>
          <td>3,999,162</td>
          <td>36,12</td>
        </tr>
        <tr>
          <td>
            <strong>Armenia</strong>
          </td>
          <td>1,383,200</td>
          <td>2,778,193</td>
          <td>49,79</td>
        </tr>
        <tr>
          <td>
            <strong>Nicaragua</strong>
          </td>
          <td>1,253,000</td>
          <td>7,088,288</td>
          <td>17,68</td>
        </tr>
        <tr>
          <td>
            <strong>Senegal</strong>
          </td>
          <td>1,247,200</td>
          <td>17,959,495</td>
          <td>6,94</td>
        </tr>
        <tr>
          <td>
            <strong>Albania</strong>
          </td>
          <td>1,228,400</td>
          <td>2,828,673</td>
          <td>43,43</td>
        </tr>
        <tr>
          <td>
            <strong>Bosnia and Herzegovina</strong>
          </td>
          <td>1,178,800</td>
          <td>3,202,057</td>
          <td>36,81</td>
        </tr>
        <tr>
          <td>
            <strong>Jamaica</strong>
          </td>
          <td>1,161,700</td>
          <td>2,825,352</td>
          <td>41,12</td>
        </tr>
        <tr>
          <td>
            <strong>Bahrain</strong>
          </td>
          <td>1,122,200</td>
          <td>1,491,279</td>
          <td>75,25</td>
        </tr>
        <tr>
          <td>
            <strong>Mongolia</strong>
          </td>
          <td>1,080,600</td>
          <td>3,467,738</td>
          <td>31,16</td>
        </tr>
        <tr>
          <td>
            <strong>Moldova</strong>
          </td>
          <td>1,073,400</td>
          <td>3,382,540</td>
          <td>31,73</td>
        </tr>
        <tr>
          <td>
            <strong>Afghanistan</strong>
          </td>
          <td>1,055,800</td>
          <td>42,726,769</td>
          <td>2,47</td>
        </tr>
        <tr>
          <td>
            <strong>Ethiopia</strong>
          </td>
          <td>1,011,200</td>
          <td>127,902,494</td>
          <td>0,79</td>
        </tr>
        <tr>
          <td>
            <strong>Lithuania</strong>
          </td>
          <td>938,600</td>
          <td>2,707,026</td>
          <td>34,67</td>
        </tr>
        <tr>
          <td>
            <strong>Ivory Coast</strong>
          </td>
          <td>919,620</td>
          <td>29,186,603</td>
          <td>3,15</td>
        </tr>
        <tr>
          <td>
            <strong>Cyprus</strong>
          </td>
          <td>858,800</td>
          <td>1,263,809</td>
          <td>67,95</td>
        </tr>
        <tr>
          <td>
            <strong>Angola</strong>
          </td>
          <td>812,800</td>
          <td>37,165,062</td>
          <td>2,19</td>
        </tr>
        <tr>
          <td>
            <strong>North Macedonia</strong>
          </td>
          <td>711,511</td>
          <td>2,083,104</td>
          <td>34,16</td>
        </tr>
        <tr>
          <td>
            <strong>Uganda</strong>
          </td>
          <td>711,100</td>
          <td>49,159,712</td>
          <td>1,45</td>
        </tr>
        <tr>
          <td>
            <strong>DR Congo</strong>
          </td>
          <td>709,400</td>
          <td>103,695,724</td>
          <td>0,68</td>
        </tr>
        <tr>
          <td>
            <strong>Cameroon</strong>
          </td>
          <td>705,700</td>
          <td>28,967,776</td>
          <td>2,44</td>
        </tr>
        <tr>
          <td>
            <strong>Trinidad and Tobago</strong>
          </td>
          <td>693,800</td>
          <td>1,536,474</td>
          <td>45,16</td>
        </tr>
        <tr>
          <td>
            <strong>Slovenia</strong>
          </td>
          <td>689,700</td>
          <td>2,119,483</td>
          <td>32,54</td>
        </tr>
        <tr>
          <td>
            <strong>Latvia</strong>
          </td>
          <td>649,000</td>
          <td>1,821,458</td>
          <td>35,63</td>
        </tr>
        <tr>
          <td>
            <strong>Laos</strong>
          </td>
          <td>643,200</td>
          <td>7,678,591</td>
          <td>8,38</td>
        </tr>
        <tr>
          <td>
            <strong>Haiti</strong>
          </td>
          <td>642,400</td>
          <td>11,786,030</td>
          <td>5,45</td>
        </tr>
        <tr>
          <td>
            <strong>Mozambique</strong>
          </td>
          <td>625,800</td>
          <td>34,309,813</td>
          <td>1,82</td>
        </tr>
        <tr>
          <td>
            <strong>Zimbabwe</strong>
          </td>
          <td>570,200</td>
          <td>16,818,780</td>
          <td>3,39</td>
        </tr>
        <tr>
          <td>
            <strong>Somalia</strong>
          </td>
          <td>567,000</td>
          <td>18,384,196</td>
          <td>3,08</td>
        </tr>
        <tr>
          <td>
            <strong>Estonia</strong>
          </td>
          <td>495,500</td>
          <td>1,321,245</td>
          <td>37,50</td>
        </tr>
        <tr>
          <td>
            <strong>Zambia</strong>
          </td>
          <td>476,900</td>
          <td>20,812,091</td>
          <td>2,29</td>
        </tr>
        <tr>
          <td>
            <strong>Montenegro</strong>
          </td>
          <td>421,500</td>
          <td>626,339</td>
          <td>67,30</td>
        </tr>
        <tr>
          <td>
            <strong>Namibia</strong>
          </td>
          <td>419,100</td>
          <td>2,620,896</td>
          <td>15,99</td>
        </tr>
        <tr>
          <td>
            <strong>Mauritius</strong>
          </td>
          <td>404,500</td>
          <td>1,301,211</td>
          <td>31,09</td>
        </tr>
        <tr>
          <td>
            <strong>Rwanda</strong>
          </td>
          <td>391,800</td>
          <td>14,232,822</td>
          <td>2,75</td>
        </tr>
        <tr>
          <td>
            <strong>Brunei</strong>
          </td>
          <td>319,920</td>
          <td>454,003</td>
          <td>70,47</td>
        </tr>
        <tr>
          <td>
            <strong>Luxembourg</strong>
          </td>
          <td>287,800</td>
          <td>657,789</td>
          <td>43,75</td>
        </tr>
        <tr>
          <td>
            <strong>Maldives</strong>
          </td>
          <td>279,800</td>
          <td>519,613</td>
          <td>53,85</td>
        </tr>
        <tr>
          <td>
            <strong>Reunion</strong>
          </td>
          <td>273,100</td>
          <td>985,101</td>
          <td>27,72</td>
        </tr>
        <tr>
          <td>
            <strong>Malta</strong>
          </td>
          <td>269,700</td>
          <td>535,815</td>
          <td>50,33</td>
        </tr>
        <tr>
          <td>
            <strong>Mali</strong>
          </td>
          <td>261,100</td>
          <td>23,600,989</td>
          <td>1,11</td>
        </tr>
        <tr>
          <td>
            <strong>Benin</strong>
          </td>
          <td>238,100</td>
          <td>13,869,824</td>
          <td>1,72</td>
        </tr>
        <tr>
          <td>
            <strong>Madagascar</strong>
          </td>
          <td>225,600</td>
          <td>30,639,254</td>
          <td>0,74</td>
        </tr>
        <tr>
          <td>
            <strong>Fiji</strong>
          </td>
          <td>221,600</td>
          <td>939,237</td>
          <td>23,59</td>
        </tr>
        <tr>
          <td>
            <strong>Iceland</strong>
          </td>
          <td>214,800</td>
          <td>376,355</td>
          <td>57,07</td>
        </tr>
        <tr>
          <td>
            <strong>Botswana</strong>
          </td>
          <td>208,200</td>
          <td>2,694,681</td>
          <td>7,73</td>
        </tr>
        <tr>
          <td>
            <strong>Guinea</strong>
          </td>
          <td>194,500</td>
          <td>14,335,115</td>
          <td>1,36</td>
        </tr>
        <tr>
          <td>
            <strong>Macau</strong>
          </td>
          <td>194,200</td>
          <td>708,027</td>
          <td>27,43</td>
        </tr>
        <tr>
          <td>
            <strong>Togo</strong>
          </td>
          <td>187,700</td>
          <td>9,143,022</td>
          <td>2,05</td>
        </tr>
        <tr>
          <td>
            <strong>Barbados</strong>
          </td>
          <td>185,700</td>
          <td>282,140</td>
          <td>65,82</td>
        </tr>
        <tr>
          <td>
            <strong>Burkina Faso</strong>
          </td>
          <td>180,600</td>
          <td>23,504,086</td>
          <td>0,77</td>
        </tr>
        <tr>
          <td>
            <strong>Guyana</strong>
          </td>
          <td>174,900</td>
          <td>816,391</td>
          <td>21,42</td>
        </tr>
        <tr>
          <td>
            <strong>Republic of the Congo</strong>
          </td>
          <td>160,900</td>
          <td>6,166,197</td>
          <td>2,61</td>
        </tr>
        <tr>
          <td>
            <strong>Gambia</strong>
          </td>
          <td>160,600</td>
          <td>2,802,644</td>
          <td>5,73</td>
        </tr>
        <tr>
          <td>
            <strong>Guadeloupe</strong>
          </td>
          <td>159,700</td>
          <td>396,057</td>
          <td>40,32</td>
        </tr>
        <tr>
          <td>
            <strong>Bhutan</strong>
          </td>
          <td>156,800</td>
          <td>789,572</td>
          <td>19,86</td>
        </tr>
        <tr>
          <td>
            <strong>Western Sahara</strong>
          </td>
          <td>155,650</td>
          <td>592,105</td>
          <td>26,29</td>
        </tr>
        <tr>
          <td>
            <strong>Martinique</strong>
          </td>
          <td>149,900</td>
          <td>366,745</td>
          <td>40,87</td>
        </tr>
        <tr>
          <td>
            <strong>Malawi</strong>
          </td>
          <td>141,500</td>
          <td>21,163,063</td>
          <td>0,67</td>
        </tr>
        <tr>
          <td>
            <strong>Bahamas</strong>
          </td>
          <td>139,200</td>
          <td>413,752</td>
          <td>33,64</td>
        </tr>
        <tr>
          <td>
            <strong>Gabon</strong>
          </td>
          <td>137,600</td>
          <td>2,457,150</td>
          <td>5,60</td>
        </tr>
        <tr>
          <td>
            <strong>Mauritania</strong>
          </td>
          <td>137,000</td>
          <td>4,918,690</td>
          <td>2,79</td>
        </tr>
        <tr>
          <td>
            <strong>Suriname</strong>
          </td>
          <td>136,800</td>
          <td>625,661</td>
          <td>21,86</td>
        </tr>
        <tr>
          <td>
            <strong>Belize</strong>
          </td>
          <td>135,100</td>
          <td>413,355</td>
          <td>32,68</td>
        </tr>
        <tr>
          <td>
            <strong>Cabo Verde</strong>
          </td>
          <td>134,900</td>
          <td>601,179</td>
          <td>22,44</td>
        </tr>
        <tr>
          <td>
            <strong>Turkmenistan</strong>
          </td>
          <td>119,700</td>
          <td>6,552,229</td>
          <td>1,83</td>
        </tr>
        <tr>
          <td>
            <strong>Liberia</strong>
          </td>
          <td>111,400</td>
          <td>5,469,307</td>
          <td>2,04</td>
        </tr>
        <tr>
          <td>
            <strong>Burundi</strong>
          </td>
          <td>111,300</td>
          <td>13,390,203</td>
          <td>0,83</td>
        </tr>
        <tr>
          <td>
            <strong>Sierra Leone</strong>
          </td>
          <td>109,500</td>
          <td>8,871,730</td>
          <td>1,23</td>
        </tr>
        <tr>
          <td>
            <strong>Chad</strong>
          </td>
          <td>100,000</td>
          <td>18,521,854</td>
          <td>0,54</td>
        </tr>
        <tr>
          <td>
            <strong>Guam</strong>
          </td>
          <td>98,000</td>
          <td>173,459</td>
          <td>56,50</td>
        </tr>
        <tr>
          <td>
            <strong>Papua New Guinea</strong>
          </td>
          <td>95,700</td>
          <td>10,410,484</td>
          <td>0,92</td>
        </tr>
        <tr>
          <td>
            <strong>Niger</strong>
          </td>
          <td>94,900</td>
          <td>27,641,257</td>
          <td>0,34</td>
        </tr>
        <tr>
          <td>
            <strong>French Guiana</strong>
          </td>
          <td>89,100</td>
          <td>315,450</td>
          <td>28,25</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Lucia</strong>
          </td>
          <td>71,700</td>
          <td>180,497</td>
          <td>39,72</td>
        </tr>
        <tr>
          <td>
            <strong>New Caledonia</strong>
          </td>
          <td>71,600</td>
          <td>294,292</td>
          <td>24,33</td>
        </tr>
        <tr>
          <td>
            <strong>Curacao</strong>
          </td>
          <td>66,700</td>
          <td>192,467</td>
          <td>34,66</td>
        </tr>
        <tr>
          <td>
            <strong>Timor Leste</strong>
          </td>
          <td>66,100</td>
          <td>1,368,944</td>
          <td>4,83</td>
        </tr>
        <tr>
          <td>
            <strong>French Polynesia</strong>
          </td>
          <td>64,900</td>
          <td>309,976</td>
          <td>20,94</td>
        </tr>
        <tr>
          <td>
            <strong>Aruba</strong>
          </td>
          <td>62,600</td>
          <td>106,242</td>
          <td>58,92</td>
        </tr>
        <tr>
          <td>
            <strong>South Sudan</strong>
          </td>
          <td>61,900</td>
          <td>11,168,390</td>
          <td>0,55</td>
        </tr>
        <tr>
          <td>
            <strong>Equatorial Guinea</strong>
          </td>
          <td>59,600</td>
          <td>1,732,031</td>
          <td>3,44</td>
        </tr>
        <tr>
          <td>
            <strong>Grenada</strong>
          </td>
          <td>55,900</td>
          <td>126,495</td>
          <td>44,19</td>
        </tr>
        <tr>
          <td>
            <strong>Eswatini</strong>
          </td>
          <td>53,320</td>
          <td>1,215,091</td>
          <td>4,39</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Vincent and the Grenadines</strong>
          </td>
          <td>53,300</td>
          <td>103,624</td>
          <td>51,44</td>
        </tr>
        <tr>
          <td>
            <strong>Cayman Islands</strong>
          </td>
          <td>52,300</td>
          <td>69,566</td>
          <td>75,18</td>
        </tr>
        <tr>
          <td>
            <strong>Andorra</strong>
          </td>
          <td>47,300</td>
          <td>80,200</td>
          <td>58,98</td>
        </tr>
        <tr>
          <td>
            <strong>Antigua and Barbuda</strong>
          </td>
          <td>45,000</td>
          <td>94,529</td>
          <td>47,60</td>
        </tr>
        <tr>
          <td>
            <strong>Jersey</strong>
          </td>
          <td>44,300</td>
          <td>103,267</td>
          <td>42,90</td>
        </tr>
        <tr>
          <td>
            <strong>Mayotte</strong>
          </td>
          <td>44,100</td>
          <td>340,322</td>
          <td>12,96</td>
        </tr>
        <tr>
          <td>
            <strong>Lesotho</strong>
          </td>
          <td>43,000</td>
          <td>2,341,547</td>
          <td>1,84</td>
        </tr>
        <tr>
          <td>
            <strong>Seychelles</strong>
          </td>
          <td>39,000</td>
          <td>107,930</td>
          <td>36,13</td>
        </tr>
        <tr>
          <td>
            <strong>Samoa</strong>
          </td>
          <td>36,300</td>
          <td>227,105</td>
          <td>15,98</td>
        </tr>
        <tr>
          <td>
            <strong>Bermuda</strong>
          </td>
          <td>36,100</td>
          <td>64,014</td>
          <td>56,39</td>
        </tr>
        <tr>
          <td>
            <strong>Isle of Man</strong>
          </td>
          <td>33,300</td>
          <td>84,794</td>
          <td>39,27</td>
        </tr>
        <tr>
          <td>
            <strong>Comoros</strong>
          </td>
          <td>30,700</td>
          <td>858,803</td>
          <td>3,57</td>
        </tr>
        <tr>
          <td>
            <strong>Guinea Bissau</strong>
          </td>
          <td>29,700</td>
          <td>2,170,568</td>
          <td>1,37</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Kitts and Nevis</strong>
          </td>
          <td>28,900</td>
          <td>47,797</td>
          <td>60,46</td>
        </tr>
        <tr>
          <td>
            <strong>Guernsey</strong>
          </td>
          <td>24,500</td>
          <td>63,649</td>
          <td>38,49</td>
        </tr>
        <tr>
          <td>
            <strong>Dominica</strong>
          </td>
          <td>24,200</td>
          <td>73,183</td>
          <td>33,07</td>
        </tr>
        <tr>
          <td>
            <strong>Faroe Islands</strong>
          </td>
          <td>24,100</td>
          <td>53,346</td>
          <td>45,18</td>
        </tr>
        <tr>
          <td>
            <strong>United States Virgin Islands</strong>
          </td>
          <td>23,400</td>
          <td>98,454</td>
          <td>23,77</td>
        </tr>
        <tr>
          <td>
            <strong>Greenland</strong>
          </td>
          <td>22,900</td>
          <td>56,714</td>
          <td>40,38</td>
        </tr>
        <tr>
          <td>
            <strong>Turks and Caicos Islands</strong>
          </td>
          <td>21,900</td>
          <td>46,225</td>
          <td>47,38</td>
        </tr>
        <tr>
          <td>
            <strong>Northern Mariana Islands</strong>
          </td>
          <td>21,900</td>
          <td>49,901</td>
          <td>43,89</td>
        </tr>
        <tr>
          <td>
            <strong>Djibouti</strong>
          </td>
          <td>20,400</td>
          <td>1,143,296</td>
          <td>1,78</td>
        </tr>
        <tr>
          <td>
            <strong>Sint Maarten</strong>
          </td>
          <td>19,800</td>
          <td>44,257</td>
          <td>44,74</td>
        </tr>
        <tr>
          <td>
            <strong>Gibraltar</strong>
          </td>
          <td>18,900</td>
          <td>32,703</td>
          <td>57,79</td>
        </tr>
        <tr>
          <td>
            <strong>Tonga</strong>
          </td>
          <td>16,600</td>
          <td>108,165</td>
          <td>15,35</td>
        </tr>
        <tr>
          <td>
            <strong>American Samoa</strong>
          </td>
          <td>15,300</td>
          <td>43,756</td>
          <td>34,97</td>
        </tr>
        <tr>
          <td>
            <strong>British Virgin Islands</strong>
          </td>
          <td>14,400</td>
          <td>31,637</td>
          <td>45,52</td>
        </tr>
        <tr>
          <td>
            <strong>Solomon Islands</strong>
          </td>
          <td>12,800</td>
          <td>747,431</td>
          <td>1,71</td>
        </tr>
        <tr>
          <td>
            <strong>Liechtenstein</strong>
          </td>
          <td>11,900</td>
          <td>39,691</td>
          <td>29,98</td>
        </tr>
        <tr>
          <td>
            <strong>Monaco</strong>
          </td>
          <td>11,700</td>
          <td>36,231</td>
          <td>32,29</td>
        </tr>
        <tr>
          <td>
            <strong>Central African Republic</strong>
          </td>
          <td>10,700</td>
          <td>5,815,270</td>
          <td>0,18</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Martin</strong>
          </td>
          <td>10,200</td>
          <td>32,195</td>
          <td>31,68</td>
        </tr>
        <tr>
          <td>
            <strong>San Marino</strong>
          </td>
          <td>10,000</td>
          <td>33,632</td>
          <td>29,73</td>
        </tr>
        <tr>
          <td>
            <strong>Vanuatu</strong>
          </td>
          <td>9,800</td>
          <td>337,876</td>
          <td>2,90</td>
        </tr>
        <tr>
          <td>
            <strong>Eritrea</strong>
          </td>
          <td>9,700</td>
          <td>3,777,777</td>
          <td>0,26</td>
        </tr>
        <tr>
          <td>
            <strong>Sao Tome and Principe</strong>
          </td>
          <td>8,900</td>
          <td>233,801</td>
          <td>3,81</td>
        </tr>
        <tr>
          <td>
            <strong>Micronesia</strong>
          </td>
          <td>8,900</td>
          <td>115,688</td>
          <td>7,69</td>
        </tr>
        <tr>
          <td>
            <strong>Anguilla</strong>
          </td>
          <td>7,800</td>
          <td>15,916</td>
          <td>49,01</td>
        </tr>
        <tr>
          <td>
            <strong>Palau</strong>
          </td>
          <td>6,600</td>
          <td>18,058</td>
          <td>36,55</td>
        </tr>
        <tr>
          <td>
            <strong>Cook Islands</strong>
          </td>
          <td>5,600</td>
          <td>17,058</td>
          <td>32,83</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Barthelemy</strong>
          </td>
          <td>5,300</td>
          <td>11,006</td>
          <td>48,16</td>
        </tr>
        <tr>
          <td>
            <strong>Marshall Islands</strong>
          </td>
          <td>4,400</td>
          <td>42,180</td>
          <td>10,43</td>
        </tr>
        <tr>
          <td>
            <strong>Nauru</strong>
          </td>
          <td>2,200</td>
          <td>12,827</td>
          <td>17,15</td>
        </tr>
        <tr>
          <td>
            <strong>Saint Pierre and Miquelon</strong>
          </td>
          <td>2,000</td>
          <td>5,828</td>
          <td>34,32</td>
        </tr>
        <tr>
          <td>
            <strong>Falkland Islands</strong>
          </td>
          <td>1,700</td>
          <td>3,797</td>
          <td>44,77</td>
        </tr>
        <tr>
          <td>
            <strong>Montserrat</strong>
          </td>
          <td>1,600</td>
          <td>4,382</td>
          <td>36,51</td>
        </tr>
        <tr>
          <td>
            <strong>Kiribati</strong>
          </td>
          <td>1,600</td>
          <td>134,496</td>
          <td>1,19</td>
        </tr>
        <tr>
          <td>
            <strong>Wallis and Futuna</strong>
          </td>
          <td>1,200</td>
          <td>11,473</td>
          <td>10,46</td>
        </tr>
        <tr>
          <td>
            <strong>Tuvalu</strong>
          </td>
          <td>1,100</td>
          <td>11,433</td>
          <td>9,62</td>
        </tr>
        <tr>
          <td>
            <strong>Niue</strong>
          </td>
          <td>450</td>
          <td>1,935</td>
          <td>23,26</td>
        </tr>
        <tr>
          <td>
            <strong>Tokelau</strong>
          </td>
          <td>100</td>
          <td>1,902</td>
          <td>5,26</td>
        </tr>
      </tbody>
    </table>
    <p>
      <em>
        {" "}
        * - The percentage of the total population to the population using the
        social networking site Instagram is an approximation. This is due to the
        fact that one person can own multiple accounts.
      </em>
    </p>
    <p>
      The number of Instagram users by country 2023 is determined, among other
      things, by a number of external factors, such as:
    </p>
    <ol>
      <li>
        The depth of internet penetration and the level of development of mobile
        communications, including the increase in bandwidth capacity of
        communication networks. When viewing photo and video data, more traffic
        is consumed.
      </li>
      <li>
        The ratio of older and younger generations. The more young people in the
        population, the higher the level of use of social networks, including
        Instagram. After all, it is young people who most often use and master
        new technologies.
      </li>
      <li>
        The level of economic development of a country. The higher the income
        level of the population, the cheaper it costs them to access mobile
        communications, gadgets and the Internet.
      </li>
      <li>
        The level and quality of development of the advertising market in the
        country. Through advertising, social networks increase their visibility
        and attract new local influencers who form a community around them. In
        this way, the culture of social networks gradually involves more people
        in the region.
      </li>
    </ol>
    <h2>Instagram Users by Country 2023 (infographic)</h2>
    <p>
      <strong>
        <img
          style={{ textAlign: "center" }}
          title="Instagram Users by Country 2023"
          src={firstimage}
          alt="Instagram Users by Country 2023"
          width="100%"
        />
      </strong>
    </p>{" "}
  </div>
</div>

                </div>
              </div>{" "}
            </div>

            {/* <span className="input-group-prepend">
            <span className="input-group-text">@</span>
          </span> */}
            {/* <input
            type="text"
            placeholder="Username"
            className="form-control"
            defaultValue=""
          />
          <div className="input-group-append">
            <button type="button" className="btn btn-primary">
              Search!
            </button>
          </div> */}
          </div>
        </div>
      </div>
    </div>
  );
}

export default ML;
